export const projects = [
  {
    slug: 'silverware',
    num: '01 / featured',
    featured: true,
    title: 'SilverWare',
    img: '/assets/Silverware.png',
    desc: 'A web application for restaurant owners to customize their store layout and manage operations. Built with a full-stack React + Django architecture deployed on AWS.',
    tags: ['ReactJS', 'Django', 'AWS', 'SQLite'],
    links: [{ label: '↗ Code', href: 'https://github.com/owendevita/Silverware' }],
    problem: 'Restaurant owners lacked a simple, flexible tool to manage store layouts and daily operations without expensive, bloated POS systems.',
    solution: 'A full-stack web application letting restaurant owners customize their floor plan, manage tables, and track operational data — all from a browser.',
    role: 'Co-developed the full stack — owned the React UI, contributed to the Django REST API, and managed the AWS EC2 deployment pipeline.',
    gallery: 4,
    architectureNodes: ['React SPA', 'Django REST API', 'AWS EC2', 'SQLite'],
  },
  {
    slug: 'econauts',
    num: '02 / featured',
    featured: true,
    title: 'EcoNauts',
    img: '/assets/EcoNauts.png',
    desc: 'An environmental placement platform connecting students with green internships and sustainability-focused organizations. Streamlines discovery and application.',
    tags: ['React', 'Python', 'REST API', 'PostgreSQL'],
    links: [{ label: '↗ Code', href: 'https://github.com/nickmarietta/GreenPlacement' }],
    problem: 'Students passionate about sustainability had no centralized place to discover green internships — opportunities were scattered across dozens of sites.',
    solution: 'A placement platform aggregating green internships, letting students filter by cause area and apply from a single unified dashboard.',
    role: 'Led front-end development — designed and built the React interface, integrated the REST API, and drove all UX decisions for the student experience.',
    gallery: 4,
    architectureNodes: ['React Frontend', 'Python REST API', 'PostgreSQL', 'Auth Layer'],
  },
  {
    slug: 'redclarity',
    num: '03',
    featured: false,
    title: 'RedClarity',
    img: '/assets/RedClarity.png',
    desc: 'A sports management application for organizing team lineups, tracking player statistics, and coordinating roster decisions across a full season.',
    tags: ['React', 'Node.js', 'MongoDB', 'Express'],
    links: [{ label: '↗ Code', href: 'https://github.com/nickmarietta/lineuplist' }],
    problem: 'Sports team managers had no simple tool to track lineups, stats, and roster changes across a season without resorting to spreadsheets.',
    solution: 'A sports management dashboard that lets managers set lineups, track per-player statistics, and coordinate roster decisions from one place.',
    role: 'Full-stack developer — built the React dashboard, Node/Express REST API, and MongoDB data layer end-to-end.',
    gallery: 3,
    architectureNodes: ['React Dashboard', 'Express API', 'MongoDB', 'Node.js Runtime'],
  },
];

export const allTags = [...new Set(projects.flatMap(p => p.tags))].sort();
